TEST : maj test to test_published

diff --git a/.github/actions/full_test_published/action.yaml b/.github/actions/full_test_published/action.yaml
--- a/.github/actions/full_test_published/action.yaml
+++ b/.github/actions/full_test_published/action.yaml
@@ -8,137 +8,117 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: test 'ytdlmusic'   
+    - name: ytdlmusic
       shell: bash      
       run: |
-        echo "test l absence d erreur sur le lancement sans parametre"
+        echo "---->ytdlmusic"
         ytdlmusic
-        echo "test le contenu du retour sur le lancement sans parametre"
+        echo "---->test the return content of ytdlmusic"
         ytdlmusic | grep "usage: "                
-    - name: test 'ytdlmusic --version'
+    - name: version
       shell: bash 
       run: |
-        echo "test l absence d erreur sur le lancement --version"
+        echo "---->ytdlmusic --version"
         ytdlmusic --version
-        echo "test le contenu du retour sur le lancement --version"
-        ytdlmusic --version | grep "ytdlmusic version             :"
-    - name: test 'ytdlmusic --help'
-      shell: bash
-      run: |
-        echo "test l absence d erreur sur le lancement --help"
-        ytdlmusic --help
-        echo "test le contenu du retour sur le lancement --help"
-        ytdlmusic --help | grep "usage: "  
-    - name: test 'ytdlmusic --auto artist title' with ffmpeg
+        echo "---->test the return content of 'ytdlmusic --version'"
+        ytdlmusic --version | grep "ytdlmusic version             :" 
+    - name: mp3
       shell: bash
       run: | 
-        echo "test l absence d erreur sur le lancement --auto"         
-        ytdlmusic --auto "Rexlambo" "Stay With Me"
-        echo "test la presence du fichier genere"
-        test -f rexlambo_stay_with_me.mp3
-        echo "test le format reel du fichier genere"
-        file -b rexlambo_stay_with_me.mp3 | grep "Audio file with ID3 version 2.4.0, contains:MPEG ADTS, layer III, v1, 256 kbps, 48 kHz, Stereo"
-    - name: test 'ytdlmusic -f --auto artist title'
+        echo '---->ytdlmusic --auto "Rexlambo Stay With Me"'         
+        ytdlmusic --auto "Rexlambo Stay With Me"
+        echo "---->test if mp3 file exists"
+        test -f "Rexlambo Stay With Me.mp3"
+        echo "---->test the mp3 file type"
+        file -b "Rexlambo Stay With Me.mp3" | grep "Audio file with ID3 version 2.4.0, contains:MPEG ADTS, layer III, v1, 256 kbps, 48 kHz, Stereo"
+    - name: m4a
       shell: bash
       run: |
-        echo "test l absence d erreur sur le lancement --auto -f"
-        ytdlmusic -f --auto "Rexlambo" "Stay With Me"
-        echo "test la presence du fichier genere"
-        test -f rexlambo_stay_with_me_1.m4a          
-    - name: test 'ytdlmusic artist title' interactive mode
-      shell: bash
-      run: |
-        echo "test l absence d erreur sur le lancement --auto -f et le non affichage du nombre de choix"          
-        printf '3\n' | ytdlmusic -f --choices 4 "Rexlambo" "Stay With Me" | grep "1-4" | wc -l | grep 1    
-        echo "test la presence du fichier genere"
-        test -f rexlambo_stay_with_me_2.m4a
-    - name: test 'ytdlmusic --auto artist title' with ffmpeg force ogg
+        echo '---->ytdlmusic -f --auto "Rexlambo Stay With Me"'  
+        ytdlmusic -f --auto "Rexlambo Stay With Me"
+        echo "---->test if m4a file exists"
+        test -f "Rexlambo Stay With Me_1.m4a"
+        echo "---->test the m4a file type"
+        file -b "Rexlambo Stay With Me_1.m4a" | grep "ISO Media, MP4 Base Media v1 \[IS0 14496-12:2003\]"
+    - name: ogg
       shell: bash
       run: | 
-        echo "test l absence d erreur sur le lancement -y -o"         
-        ytdlmusic -yo "Rexlambo" "Stay With Me"
-        echo "test la presence du fichier genere"
-        test -f rexlambo_stay_with_me.ogg
-        echo "test le format reel du fichier genere"
-        file -b rexlambo_stay_with_me.ogg | grep -b "Ogg data, Vorbis audio, stereo, 48000 Hz, ~112000 bps"                               
+        echo '---->ytdlmusic -yo "Rexlambo Stay With Me"' 
+        ytdlmusic -yo "Rexlambo Stay With Me"
+        echo "---->test if ogg file exists"
+        test -f "Rexlambo Stay With Me.ogg"
+        echo "---->test the ogg file type"
+        file -b "Rexlambo Stay With Me.ogg" | grep -b "Ogg data, Vorbis audio, stereo, 48000 Hz, ~112000 bps"                                                
     - name: test downloaded files
       shell: bash
       run: |
-        echo "affiche le md5 de rexlambo_stay_with_me"            
-        md5sum rexlambo_stay_with_me.m4a
-        echo "affiche le md5 de rexlambo_stay_with_me_1" 
-        md5sum rexlambo_stay_with_me_1.m4a
-        echo "les md5 doivent etre differents car urls differentes"
-        test "$(md5sum rexlambo_stay_with_me.m4a | cut -d " " -f 1)" != "$(md5sum rexlambo_stay_with_me_1.m4a | cut -d " " -f 1)"
-    - name: test 'ytdlmusic --auto artist title' with force m4a
-      shell: bash
-      run: |      
-        echo "test l absence d erreur sur le lancement en forcage --m4a"    
-        ytdlmusic --auto --m4a "Rexlambo" "Stay With Me"
-        echo "test la presence du fichier genere"
-        test -f rexlambo_stay_with_me_2.m4a       
-    - name: test batch
+        echo '---->md5sum "Rexlambo Stay With Me.m4a"'    
+        md5sum "Rexlambo Stay With Me.m4a"
+        echo '---->md5sum "Rexlambo Stay With Me_1.m4a"' 
+        md5sum "Rexlambo Stay With Me_1.m4a"
+        echo '---->md5sum should be differents because from differents urls' 
+        test "$(md5sum 'Rexlambo Stay With Me.m4a' | cut -d " " -f 1)" != "$(md5sum 'Rexlambo Stay With Me_1.m4a' | cut -d " " -f 1)"     
+    - name: batch
       shell: bash
       run: |
-        echo "launch batch and verify three downloads"
-        ytdlmusic --auto --batch "./test/test.csv" "True" ";" 2 1 | grep "is ready" | wc -l | grep 3
-        echo "test la presence des trois fichiers"
-        test -f above_limujii.mp3
-        test -f awake_nomyn.mp3
-        test -f avalon_scandinavianz.mp3
+        echo '---->ytdlmusic --auto --batch "./test/test.csv" "True" ";" 2+1'
+        ytdlmusic --auto --batch "./test/test.csv" "True" ";" 2+1
+        echo '---->test the existence of the three files'
+        test -f "above limujii.mp3" && test -f "awake nomyn.mp3" && test -f "avalon scandinavianz.mp3"
     - name: test bad launch
       shell: bash
-      run: |  
-        echo "verifie le code erreur 2"        
-        (ytdlmusic --tetet || echo $?) | grep "2"   
-    - name: test short params
-      shell: bash
-      run: |
-        echo "test une combinaison de flags courts"          
-        ytdlmusic -fyd "Rexlambo" "Stay With Me"
-        echo "test l existence du fichier généré"
-        test -f rexlambo_stay_with_me_3.m4a  
-    - name: test bad launch short params
-      shell: bash
-      run: |
-        echo "verifie le code erreur 2 "            
-        (ytdlmusic -dvUz || echo $?) | grep "2"     
-    - name: test missing dependency error
+      run: | 
+        echo "---->ytdlmusic --tetet verify is error" 
+        ytdlmusic --tetet || echo "error is ok"
+        echo "---->verify error code"        
+        (ytdlmusic --tetet || echo $?) | grep "2"       
+    - name: missing dependency error + upgrade
       shell: bash
       run: | 
-        echo "retire une dependance"         
+        echo "---->remove dependency"        
         pip uninstall --yes youtube-dl
-        echo "verifie la version" 
+        echo "---->verify is version not installed"
         ytdlmusic --version | grep "youtube-dl version            : NOT INSTALLED"
-        echo "verifie que l erreur est remontee" 
-        (ytdlmusic --auto "Rexlambo" "Stay With Me" || echo "good exit code") | grep "good exit code"
-        echo "verifie que l erreur est propre" 
-        (ytdlmusic --auto "Rexlambo" "Stay With Me" || echo "good exit code") | grep "Try to upgrade with 'ytdlmusic --update'"
-    - name: test repair full-update
-      shell: bash
-      run: |  
-        echo "verifie l upgrade"               
+        echo "---->verify the error" 
+        (ytdlmusic --auto "Rexlambo Stay With Me" || echo "good exit code") | grep "good exit code"
+        echo "---->verify the error is corretly displayed" 
+        (ytdlmusic --auto "Rexlambo Stay With Me" || echo "good exit code") | grep "Try to upgrade with 'ytdlmusic --update'"
+        echo "---->test upgrade contains waited text"               
         printf 'y\n' | ytdlmusic --fullupdate | grep "Successfully installed youtube-dl"
-        echo "verifie que l application refonctionne en HQ"
-        ytdlmusic -dkQ --auto "Rexlambo" "Stay With Me"
-        echo "verifie le quiet est fonctionnel"
-        ytdlmusic --auto -q "Rexlambo" "Stay With Me" | grep "ffmpeg" || echo "ffmpeg non trouve" | grep "ffmpeg non trouve"
-        echo "les md5 doivent etre differents (un en HQ l autre non)"
-        md5sum rexlambo_stay_with_me_2.mp3
-        md5sum rexlambo_stay_with_me_1.mp3
-        test "$(md5sum rexlambo_stay_with_me_2.mp3 | cut -d " " -f 1)" != "$(md5sum rexlambo_stay_with_me_1.mp3 | cut -d " " -f 1)"        
-        echo "verifie le telechargement keep"
-        ytdlmusic -dkQ --auto "avalon" "scandinavianz"
-        echo "verifie le nom genere"
-        test -f avalon_scandinavianz_no_copyright_music_.mp3
-        echo "verifie que l upgrade n esy plus disponible"
-        printf 'y\n' | ytdlmusic --fullupdate | grep "Requirement already satisfied" | wc -l | grep 3
-    - name: test bad launch (one parameter)
+        echo '---->ytdlmusic -dkQ --auto "Rexlambo Stay With Me"'
+        ytdlmusic -q --auto "Rexlambo Stay With Me"
+        echo "---->test if mp3 file exists"
+        test -f "Rexlambo Stay With Me_1.mp3"  
+        echo "---->test unaivaible upgrade"
+        printf 'y\n' | ytdlmusic --fullupdate | grep "Requirement already satisfied" | wc -l | grep 3              
+    - name: HQ
       shell: bash
-      run: |   
-        echo "ytdlmusic tetet renvoie un code erreur different de 0"       
-        (ytdlmusic tetet || echo "good exit code") | grep "good exit code"
-        echo "ytdlmusic tetet renvoie un Missing song"
-        (ytdlmusic tetet || echo "good exit code") | grep "Missing song"  
-        echo "ytdlmusic --n 13 renvoie un code erreur 2 (argparse)"
-        (ytdlmusic -n 13 "Rexlambo" "Stay With Me" || echo $?) | grep "2"           
+      run: |         
+        echo '---->ytdlmusic -dQ --auto "Rexlambo Stay With Me"'
+        ytdlmusic -dQ --auto "Rexlambo Stay With Me"
+        echo '---->md5sum "Rexlambo Stay With Me.mp3"'    
+        md5sum "Rexlambo Stay With Me.mp3"
+        echo '---->md5sum "Rexlambo Stay With Me_2.mp3"'    
+        md5sum "Rexlambo Stay With Me_2.mp3"
+        echo '---->md5sum should be differents because from differents qualities' 
+        test "$(md5sum 'Rexlambo Stay With Me.mp3' | cut -d " " -f 1)" != "$(md5sum 'Rexlambo Stay With Me_2.mp3' | cut -d " " -f 1)"  
+    - name: keep
+      shell: bash
+      run: |           
+        echo '---->ytdlmusic -dkQ --auto "avalon scandinavianz"'
+        ytdlmusic -dkQ --auto "avalon scandinavianz"
+        echo '---->verify the filename'
+        test -f "Avalon Scandinavianz No Copyright Music.mp3"         
+    - name: tag
+      shell: bash
+      run: |           
+        echo '---->ytdlmusic -tyq "avalon scandinavianz"'
+        ytdlmusic -tyq "avalon scandinavianz"
+        echo '---->verify the filename'
+        test -f "Audio Library Music for content creators - Avalon Scandinavianz No Copyright Music.mp3" 
+        echo '---->ytdlmusic -tyqf "avalon scandinavianz"'
+        ytdlmusic -tyqf "avalon scandinavianz"
+        echo '---->verify the filename (with keeyoutubename)'
+        test -f "Avalon Scandinavianz No Copyright Music.m4a"
+
+
