FEATURE: --quality // --keep // --n // --quiet

diff --git a/.github/actions/full_test/action.yaml b/.github/actions/full_test/action.yaml
--- a/.github/actions/full_test/action.yaml
+++ b/.github/actions/full_test/action.yaml
@@ -92,7 +92,7 @@ runs:
       shell: bash
       run: |               
         printf 'y\n' | ytdlmusic --full-update | grep "Update available"
-        ytdlmusic --auto -q "Rexlambo" "Stay With Me" | grep "ffmpeg" || echo "lof ffmpeg non trouve") | grep "good exit code"
+        ytdlmusic --auto -q "Rexlambo" "Stay With Me" | grep "ffmpeg" || echo "ffmpeg non trouve" | grep "ffmpeg non trouve"
         ytdlmusic -dkQ --auto "Rexlambo" "Stay With Me" | grep "320"
         test -f avalon_scandinavianz_no_copyright_music_.mp3
         printf 'y\n' | ytdlmusic --full-update | grep "No update available"
@@ -100,4 +100,5 @@ runs:
       shell: bash
       run: |          
         (ytdlmusic --tetet || echo "good exit code") | grep "good exit code"
-        (ytdlmusic --tetet || echo "good exit code") | grep "Missing song"            
+        (ytdlmusic --tetet || echo "good exit code") | grep "Missing song"   
+        (ytdlmusic --n=13 "Rexlambo" "Stay With Me" || echo "good exit code") | grep "13 is not valid"           
