FEATURE: --quality // --keep // --n // --quiet

diff --git a/.github/actions/full_test/action.yaml b/.github/actions/full_test/action.yaml
--- a/.github/actions/full_test/action.yaml
+++ b/.github/actions/full_test/action.yaml
@@ -32,7 +32,7 @@ runs:
     - name: test 'ytdlmusic artist title' interactive mode
       shell: bash
       run: |          
-        printf '3\n' | ytdlmusic -f "Rexlambo" "Stay With Me"
+        printf '3\n' | ytdlmusic -f --n=4 "Rexlambo" "Stay With Me" | grep "1-4" | wc -l | grep 1
         test -f rexlambo_stay_with_me_2.m4a
     - name: test 'ytdlmusic --auto artist title' with ffmpeg
       shell: bash
@@ -91,5 +91,15 @@ runs:
     - name: test repair full-update
       shell: bash
       run: |               
-        printf 'y\n' | ytdlmusic --full-update
-        ytdlmusic --auto "Rexlambo" "Stay With Me"      
+        printf 'y\n' | ytdlmusic --full-update | grep "Update available"
+        ytdlmusic --auto -q "Rexlambo" "Stay With Me" | grep "ffmpeg" || echo "lof ffmpeg non trouve") | grep "good exit code"
+        ytdlmusic -dkQ --auto "Rexlambo" "Stay With Me" | grep "320"
+        test -f avalon_scandinavianz_no_copyright_music_.mp3
+        printf 'y\n' | ytdlmusic --full-update | grep "No update available"
+    - name: test bad launch (one parameter)
+      shell: bash
+      run: |          
+        (ytdlmusic --tetet || echo "good exit code") | grep "good exit code"
+        (ytdlmusic --tetet || echo "good exit code") | grep "Missing song"            
+      #TODO
+      #add number 
